### PR TITLE
Mark some Mastodon clients as archived.

### PR DESCRIPTION
**Pull request by orowith2os**
Bleh, forgot to put it on a dev branch~~~~

### CODE REVIEW

**Comment by ltGuillaume** [comment]
You might as well ass Tusky's fork [Husky](https://git.sr.ht/~captainepoch/husky) ([F-Droid](https://f-droid.org/en/packages/su.xash.husky)) for the Pleroma support then.

**Comment by orowith2os** [comment]
Done!

**Comment by HookedBehemoth** [comment]
Fedilab seems to live on here https://codeberg.org/tom79/Fedilab
Can you fully remove the archived ones?

**Comment by rilysh** [comment]
Tootle client development seems to moved on [Gnome GitLab](https://gitlab.gnome.org/World/tootle). But there isn't any commit done yet.

**Pull request closed without merging**
