### PR TITLE
Add Porn section

### PR DESCRIPTION
**Pull request by Leichesters**
Hey, this isn't spam but lets add a section for awesome alternative frontends for porn sites. Some countries block such sites.

### CODE REVIEW

**Comment by mendel5** [comment]
@Leichesters 

https://youtu.be/LTJvdGcb7Fs?t=10 

👍

**Comment by Leichesters** [comment]
@mendel5 could you merge this please?

**Comment by HookedBehemoth** [comment]
While this seems to be unmaintained, it still works. It would be nice to have more than one sample in this category.

**Comment by Leichesters** [comment]
@HookedBehemoth Unfortunately I don't know of any other alternative frontends for porn :/

**Pull request merged**
