### PR TITLE
Add Gtkcord and Ripcord for Discord. Include 'Discord' section

### PR DESCRIPTION
**Pull request by zesterer**

### CODE REVIEW

**Comment by mendel5** [comment]
Links:
- https://github.com/diamondburned/gtkcord3/
- https://cancel.fm/ripcord/

**Comment by mendel5** [comment]
Thanks for your input, @zesterer .

While Ripcord seems like an interesting application, unfortunately it appears to be closed source and not available under a free license?

**Comment by zesterer** [comment]
That's a good point, I shall remove it.

**Comment by zesterer** [comment]
Do you have a merge & squash option?

**Comment by mendel5** [comment]
> That's a good point, I shall remove it.

When I look at https://github.com/mendel5/alternative-front-ends/pull/44/commits/8f520060a70e08201f882e64c74d9317f92a3103 it appers you have removed the open source front end for Discord while Ripcord is still included 😅 

No worries, I'll fix it.

> Do you have a merge & squash option?

Yes

**Comment by mendel5** [comment]
> Urgh, apologies, busy morning. Not thinking straight. Thanks for fixing it!

Sure, no problem! gtkcord3 has been added.

Commit: https://github.com/mendel5/alternative-front-ends/commit/02e3187d659c45f1672f57bcc6eaffa7aa4b7076

**Pull request merged**
