### PR TITLE
Remove link to bibliogram repo on Github

### PR DESCRIPTION
**Pull request by caminsha**
I removed the link for the source repository from bibliogram as the site is not available anymore.

### CODE REVIEW

**Comment by Mennaruuk** [comment]
It would be great if you can add in the correct link for the repo: https://sr.ht/~cadence/bibliogram/

**Comment by mendel5** [comment]
Hi @caminsha , thanks for your contribution!

Your pull request has been merged. Commit: https://github.com/mendel5/alternative-front-ends/commit/cd94453668120061d68c6cba6ceb3e628dd5b340

@Mennaruuk : The correct link to the Bibliogram repo at https://sr.ht/~cadence/bibliogram/ is already included.

**Comment by caminsha** [comment]
Hi, thanks for merging my pull request.

**Comment by mendel5** [comment]
Sure!

**Pull request merged**
