### PR TITLE
Suggest Kizie.co for Twitter

### PR DESCRIPTION
**Pull request by rishimohan**
Hi, I want to suggest kizie.co as a free Twitter client for Web. Kizie has almost all the features from Twitter.com, minus ads and all the clutter.

### CODE REVIEW

**Comment by rishimohan** [comment]
My bad I created PR for it right away, force of habit 😅.

**Comment by mendel5** [comment]
Thanks for your input, @rishimohan .

It seems that Kizie.co is a proprietary service and its source code is not available to the public under a free license. If you know where I can find the source code please let me know.

**Comment by rishimohan** [comment]
@mendel5 Oh, right it's not open-source yet. I missed reading the repo description that it lists only open-source alternatives. Feel free to close to PR if that's the case. 

I thought as a indie-hacker my work could've been relevant addition to the list :)

**Comment by mendel5** [comment]
Thanks for your fast reply.

> I thought as a indie-hacker my work could've been relevant addition to the list

Your work is still appreciated!

**Comment by mendel5** [comment]
Pull request closed because the source code for Kizie.co is unfortunately not open source or available under a free license.

**Pull request closed without merging**
